=== CRUD Repositories

In this section, we will introduce the Spring framework's inbuilt support for such CRUD operations via the `org.springframework.data.repository.CrudRepository` interface and will show how to use such repositories to implement your use cases in so-called _service_ classes.

If you would like to, you can obtain a version of the project that already has the code for the backend and model classes from the previous tutorials: https://github.com/McGill-ECSE321-Fall2025/event-registration/tree/6c1472fa2024a6fd0a5af38bde27e6ff3ff44a64/src/main/java/ca/mcgill/ecse321/eventregistration.

==== Creating a CRUD Repository

. Create a new interface `PersonRepository` in the `ca.mcgill.ecse321.eventregistration.repository` package and extend the `CrudRepository<Person, String>` interface.

. Create a new method `Person findById(int id)`. +
_PersonRepository.java_
+
[source,java]
----
package ca.mcgill.ecse321.eventregistration.repository;

import org.springframework.data.repository.CrudRepository;

import ca.mcgill.ecse321.eventregistration.model.Person;

public interface PersonRepository extends CrudRepository<Person, Integer>{
	
	Person findPersonById(int id);
	
}
----

. Since Spring supports automated JPA Query creation from method names (see link:https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.query-creation[possible language constructs here]) **we don't need to implement the interface manually**, Spring JPA will create the corresponding queries runtime! This way we don't need to write SQL queries either.

Create interfaces for the `Event` and `Registration` classes as well.