=== Testing the Persistence Layer
Now we will write some tests to verify that our persistence layer is working as expected.

==== Writing a Test
The basic structure of a repository layer test is:

. Create a new object.
. Save the object to the database using the repository.
. Read the object from the database using the repository.
. Assert that the object from the database has the correct attributes.

Use dependency injection (via the `@Autowired` annotation) to get an instance of your repository. Also add the `@Test` annotation to each test method.

You will want to clear the database after each run so that you don't waste storage space and avoid violating any unique constraints. Define a method `clearDatabase()` with the annotation `@AfterEach` that clears all relevant tables. *Make sure you clear your dependent classes prior to clearing your independent classes, as operations _only_ cascade if the associative relationship is a composition!*

For example, the test class for the `PersonRepository` should be similar to the following code. The package and import statements have been omited for clarity.

```java 
@SpringBootTest
public class PersonRepositoryTests {
	@Autowired
	private PersonRepository personRepository;

	@AfterEach
	public void clearDatabase() {
		personRepository.deleteAll();
	}

	@Test
	public void testPersistAndLoadPerson() {
		// Create person
		String name = "Muffin Man";
		String emailAddress = "muffin.man@gmail.com";
		String password = "i_love_muffins";
		Person muffinMan = new Person();
		muffinMan.setName(name);
		muffinMan.setEmailAddress(emailAddress);
		muffinMan.setPassword(password);

		// Save person
		muffinMan = personRepository.save(person);
		int id = muffinMan.getId();

		// Read person from database
		Person muffinManFromDb = personRepository.findPersonById(id);

		// Assert correct response
		assertNotNull(person);
		assertEquals(muffinManFromDb.getName(), name);
		assertEquals(muffinManFromDb.getEmailAddress(), emailAddress);
		assertEquals(muffinManFromDb.getPassword(), password);
	}
}
```

==== Running the Tests
To run the tests, `cd` into the `EventRegistration` folder and issue the command `./gradlew test`.


==== Debugging Failing Tests
You will almost certainly encounter failing tests at some point. When this happens, it is usually helpful to read the stack trace and see if there are any helpful hints. At first you will probably find that the stack traces are short and not very informative. Add the following snippet inside the `test` task in your `build.gradle` file:
```
testLogging {
	exceptionFormat "full"
	//...other configurations
}
```
Re-run the tests and you should see much longer stack traces with helpful hints.
Alternatively, you can check the test report for the full stack traces.
There should be a link to the report in the output of `gradlew`.
In either case, focus on the "Caused by:" parts.
The error messages go from high-level to low-level, so if you find the messages at the beginning too vague then you might be better off reading the stack trace bottom-up.

If _all_ the tests are failing (including `contextLoads()`), it means your project failed to start. This is generally because it failed to connect to the database or there is an issue with your model.

===== Common Errors
- Missing or badly-formatted data in `application.properties`. You need a database driver, the URL of an existing database, a username, and a password. The database URL is particularly easy to mess up: it needs to follow the format `jdbc:postgresql://localhost:port/database_name`.
- Using reserved keywords for class names (e.g., `User`). This will result in a nasty SQL syntax error.
- Incorrectly named repository methods. For example, if you have a property `eventName` and you call your repository method `findEventByName()`, Spring will complain that there's no property called `name` in the `Event` class. Call the method `findEventByEventName()` instead!
- Missing annotations. For example, if you forget an `@Id` annotation, Spring will complain that there's no unique identifier for your class.
